package com.ricardotrujillo.prueba.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ricardotrujillo.prueba.model.db.Store;

import com.ricardotrujillo.prueba.model.db.StoreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storeDaoConfig;

    private final StoreDao storeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        storeDao = new StoreDao(storeDaoConfig, this);

        registerDao(Store.class, storeDao);
    }
    
    public void clear() {
        storeDaoConfig.getIdentityScope().clear();
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

}
