package com.ricardotrujillo.prueba.model.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORE".
 */
public class Store {

    private Long id;
    private String objectId;
    private String object;

    public Store() {
    }

    public Store(Long id) {
        this.id = id;
    }

    public Store(Long id, String objectId, String object) {
        this.id = id;
        this.objectId = objectId;
        this.object = object;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getObject() {
        return object;
    }

    public void setObject(String object) {
        this.object = object;
    }

}
